### PR TITLE
[Documentation] Update JS packages

### PR DESCRIPTION
**Pull request by Batta32**
### Purpose
*What is the context of this pull request? Why is it being done?*
The main README is outdated.

### Changes
*Are there any changes that need to be called out as significant or particularly difficult to grasp? (Include illustrative screenshots for context if applicable.)*
Update the packages' version of the main README.

### Tests
*Is this covered by existing tests or new ones? If no, why not?*
\-

### Feature Plan
*Are there any remaining steps or dependencies before this issue can be fully resolved? If so, describe and link to any relevant pull requests or issues.*
\-

#### General
- [ ] I have commented my code, particularly in hard-to-understand areas	
- [ ] I have added or updated the appropriate tests	
- [X] I have updated related documentation

### CODE REVIEW

**Comment by dfavretto** [comment]
The changes look great! But the badge is not being rendered 😟
image

**Comment by Batta32** [comment]
Weird, I can see it 
image

**Comment by dfavretto** [comment]
Now I see the badges :confusion:

**Comment by Batta32** [comment]
Already merged in MS!

**Pull request closed without merging**
